### ISSUE TITLE
INI file only has 3 params but script expects 4

### ISSUE THREAD

**Issue by Sergong** [Azure-Samples/virtual-machines-python-scheduled-events-central-logging#2]
Getting following error when running this on my Azure VM with Python 3.5.3 installed:
C:\Scripts>python scheduledEventsInteractiveTool.py
 2017-04-19 17:46:01,768 [DEBUG] Azure Scheduled Events Interactive Tool
 2017-04-19 17:46:01,768 [DEBUG] get_scheduled_events was called
 2017-04-19 17:47:02,055 [INFO] handle_scheduled_events was called with 0
Traceback (most recent call last):
  File "scheduledEventsInteractiveTool.py", line 126, in <module>
    main()
  File "scheduledEventsInteractiveTool.py", line 122, in main
    handle_scheduled_events(data)
  File "scheduledEventsInteractiveTool.py", line 94, in handle_scheduled_events
    send_to_event_hub(ehMsg)
  File "scheduledEventsInteractiveTool.py", line 66, in send_to_event_hub
    ehMsgSender = EventHubMsgSender()
  File "scheduledEventsInteractiveTool.py", line 39, in __init__
    endPoint, keyName, keyValue, entityPath = [sub[sub.index('=') + 1:] for sub
in connectionString.split(";")]
ValueError: not enough values to unpack (expected 4, got 3)

This is the content of my INI (keys deliberately masked)
[DEFAULT] connectionstring = Endpoint=sb://Update-Hub.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=*********************************************

Haven't gotten to the point of trying to reach the IoT Hub yet but I suspect that .servicebus.windows.net may not be the correct suffix either as my connection string has the following suffix in the portal: .azure-devices.net

**Comment by EliPinkertonMicrosoft** [comment]
Thanks for raising @Sergong, it appears that the lack of documentation for EntityPath was an oversight.

For a short term fix, you should be able to modify the .ini file to include the expected EntityPath, which is the name of your specific EventHub. See the modified connection string below

<pre>
connectionstring = Endpoint=sb://[your-namespace].servicebus.windows.net/;SharedAccessKeyName=[your-sas-key-name];SharedAccessKey=[your-sas-psw];<b>EntityPath=[your-eventhub-name]</b>
</pre>

I've submitted a bundle of various changes in [this PR](https://github.com/Azure-Samples/virtual-machines-python-scheduled-events-central-logging/pull/5) that should address and fix this problem.

**Comment by zivraf** [comment]
Thank you for this comment. We have fixed the ini file added entitypath to the end of the Event Hub connection string
